#!/bin/bash -ex
exec | tee /etc/atlantis/scripts/build.log
exec 2>&1

OVERLAY=$1
cp -dR --preserve=mode $OVERLAY/* /

pushd /etc/service
  ln -s /etc/sv/app* .
popd

if [ -d /src/check_mk_checks ]; then
  mv /src/check_mk_checks /
fi

mkdir -p /app/target
mkdir -p /app/config

find /src/target -name \*.jar /app/target
cp -R /src/config /app/config

pushd /app
  /etc/atlantis/scripts/setup
popd
chown -R user1:user1 /app

echo "done building app"
