#!/bin/bash -ex
exec > /sbin/provision_type.log 2>&1

OVERLAY=$1
cp -dR --preserve=mode $OVERLAY/* /

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y build-essential

pushd /usr/local && curl -sL https://go.googlecode.com/files/go1.1.2.linux-amd64.tar.gz | tar -xz && popd
pushd /usr/bin && for x in $(find /usr/local/go/bin -type f); do ln -s $x; done && popd
