#!/bin/bash -ex
## Copyright 2014 Ooyala, Inc. All rights reserved.
##
## This file is licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
## except in compliance with the License. You may obtain a copy of the License at
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software distributed under the License is
## distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and limitations under the License.

exec > /sbin/provision_type.log 2>&1

OVERLAY=$1
cp -dR --preserve=mode $OVERLAY/* /

pushd /usr/local && curl -sL https://go.googlecode.com/files/go1.1.2.linux-amd64.tar.gz | tar -xz && popd
pushd /usr/bin && for x in $(find /usr/local/go/bin -type f); do ln -s $x; done && popd
