#!/bin/bash -ex
exec > /sbin/provision_type.log 2>&1

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y apache2 php5 libapache2-mod-php5 php5-mcrypt

OVERLAY=$1
cp -dR --preserve=mode $OVERLAY/* /
