# Ruby 1.9.3 Base Image
#
# VERSION 0.0.4

FROM __REGISTRY_HOST__/base/precise64-0.0.4
MAINTAINER __MAINTAINER__

# Install Ruby and Bundler
RUN apt-get update
RUN apt-get install -y ruby1.9.3
RUN apt-get install -y ruby1.9.1-dev
RUN echo 'gem: --no-ri --no-rdoc' > /root/.gemrc
RUN gem install bundler
