#!/bin/bash -ex
exec | tee /etc/atlantis/scripts/build.log
exec 2>&1

OVERLAY=$1
cp -dR --preserve=mode $OVERLAY/* /

pushd /etc/service
  ln -s /etc/sv/app* .
popd

if [ -d /src/check_mk_checks ]; then
  mv /src/check_mk_checks /
fi
mv /src /app

bundler install --gemfile /app/Gemfile

pushd /app
  /etc/atlantis/scripts/setup
popd
chown -R user1:user1 /app

truncate -s 0 /etc/resolv.conf

echo "done building app"
