# Base Atlantis Image
#
# VERSION 0.0.4

FROM __BASE_IMAGE__
MAINTAINER __MAINTAINER__

# insert provision and run the script
RUN mkdir -p /provision/precise64
ADD provision /provision/precise64/
RUN /provision/precise64/provision.sh 2>&1 >/provision/precise64/provision.log

# Setup default run command
CMD runsvdir /etc/service
