# Go Base Image
#
# VERSION 0.1.0

FROM __REGISTRY_HOST__/base/precise64-0.1.0
MAINTAINER __MAINTAINER__

# Install Make
RUN apt-get update
RUN apt-get install -y make

# Install Go
RUN cd /usr/local && curl -sL https://go.googlecode.com/files/go1.2.linux-amd64.tar.gz |tar -xz
RUN cd /usr/bin && for f in `ls /usr/local/go/bin`; do ln -s /usr/local/go/bin/$f; done
