#!/bin/bash -ex
exec > /sbin/provision_type.log 2>&1

OVERLAY=$1
cp -dR --preserve=mode $OVERLAY/* /

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y ruby1.9.3 ruby1.9.1-dev

echo "gem: --no-ri --no-rdoc" > /root/.gemrc
gem install bundler
