# python 2.7.3 Base Image
#
# VERSION 0.1.0

FROM __REGISTRY_HOST__/base/precise64-0.1.0
MAINTAINER __MAINTAINER__

# Install Pip (Python is already in our precise64 base image.
# Ubuntu has an old version, so install via easy_install.
RUN apt-get update
RUN apt-get install -y python-setuptools
RUN easy_install pip
